language: android
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

# bug https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "platforms;android-27"

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file_glob: true
    file:
      - "build/outputs/aar/*.aar"
      - "build/libs/*.jar"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew artifactoryPublish
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true
